# Entmax-DPO via Fenchel–Young scores (margin-limited softplus)
name: endpo

# entmax parameter (smooth sparsity). 1<alpha<2; try 1.3–1.6
alpha: 1.5

# DPO scale on model-vs-ref score difference
beta: 0.1

# margin γ and temperature τ for the “margin-limited softplus”
gamma: 0.5
tau: 1.0

# Optional: whether to average scores by valid token count (length-normalized)
length_normalize: false

# Optional: if true, drop the reference (ΔS_ref=0)
reference_free: false