# sparsemax-based DPO (Fenchel–Young score)
name: sp_dpo

# logistic temperature (tune in ~0.05–0.5)
beta: 0.1
label_smoothing: 0
# if true, ignore reference model (maximum-entropy reference)
reference_free: false